### ISSUE TITLE
Silly Question

### ISSUE THREAD

**Issue by hirenshah** [rhyous/EasyXml#1]
This may sound really silly, but I've added this to my solution using nuget.  I am reading in a XML file as XDocument, and how do I actually linearize and pretty print it?

**Comment by rhyous** [comment]
Wow, I never saw this question until now. Probably years to late, but just create an instance of the Rhyous.EasyXml.Xml object, which takes the Xml as a string. 

```
var xml = new Xml(xmlText);
var pretty = xml.PrettyXml;
```

You can also update the xml.PrettySettings before you do so.

**Comment by hirenshah** [comment]
Haha, to be honest, I don't even remember what I was using this for 😂
